import { MediaLog } from './types';

export const INITIAL_MEDIA_LOGS: MediaLog[] = [
  {
    id: 'f87a32d1-9b1e-436d-9b55-6b216c87e101',
    tmdb_id: 693134,
    title: 'Dune: Part Two',
    media_type: 'movie',
    release_year: 2024,
    runtime_minutes: 166,
    poster_url: 'https://image.tmdb.org/t/p/w780/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg',
    backdrop_url: 'https://image.tmdb.org/t/p/original/xOMo8BRK7PfcJv9JCnx7s5200fr.jpg',
    director: 'Denis Villeneuve',
    cast: ['Timothée Chalamet', 'Zendaya', 'Rebecca Ferguson', 'Austin Butler', 'Javier Bardem'],
    genres: ['Science Fiction', 'Adventure'],
    watched_date: '2024-03-01',
    personal_rating: 9.6,
    gut_reaction: 'A cathedral of monolithic sound and sand that made my teeth vibrate for 166 unrelenting minutes.',
    full_review: 'Villeneuve accomplishes the impossible: rendering Herbert’s dense, skeptical theological deconstruction into an operatic blockbuster that never bends to fan service. Greig Fraser’s infrared Giedi Prime arena sequence is one of the boldest aesthetic departures in modern cinema. Austin Butler’s Feyd-Rautha radiates chilling psychotic precision, while Zimmer’s auditory onslaught shakes the core.',
    mood_coordinates: { x: -25, y: 20 },
    custom_tags: ['Mind-Melting', 'Audio Masterpiece', 'Epic Odyssey', 'Sci-Fi Royalty'],
    dominant_color: '#e28834',
    rewatch_count: 2,
    created_at: '2024-03-02T10:00:00Z'
  },
  {
    id: 'e49b81a2-3f11-4a8e-a901-7c593a11b202',
    tmdb_id: 545611,
    title: 'Everything Everywhere All at Once',
    media_type: 'movie',
    release_year: 2022,
    runtime_minutes: 139,
    poster_url: 'https://image.tmdb.org/t/p/w780/w3LxiVYuanWRaqnyHTZ4kH6qQe6.jpg',
    backdrop_url: 'https://image.tmdb.org/t/p/original/70Rm9m1mb9T05115d7v71NDNswE.jpg',
    director: 'Daniel Kwan, Daniel Scheinert',
    cast: ['Michelle Yeoh', 'Ke Huy Quan', 'Stephanie Hsu', 'Jamie Lee Curtis'],
    genres: ['Action', 'Adventure', 'Science Fiction', 'Comedy'],
    watched_date: '2022-04-10',
    personal_rating: 9.8,
    gut_reaction: 'A maximalist, bagel-shaped existential panic attack transformed into the most tender tearful hug imaginable.',
    full_review: 'The Daniels weaponize sheer ADHD cinematic velocity to answer 21st-century nihilism with radical empathy. Michelle Yeoh gives the performance of a lifetime, but it is Ke Huy Quan’s gentle speech about kindness in a cruel world that broke me in the theater and reframed how I want to live.',
    mood_coordinates: { x: 70, y: 85 },
    custom_tags: ['Existential Catharsis', 'Multiverse Chaos', 'Pure Genius', 'Tearjerker'],
    dominant_color: '#c93b74',
    rewatch_count: 4,
    created_at: '2022-04-11T12:30:00Z'
  },
  {
    id: 'a12c44e9-7712-421d-8f92-93b76251c303',
    tmdb_id: 335984,
    title: 'Blade Runner 2049',
    media_type: 'movie',
    release_year: 2017,
    runtime_minutes: 164,
    poster_url: 'https://image.tmdb.org/t/p/w780/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg',
    backdrop_url: 'https://image.tmdb.org/t/p/original/ilRyAZstrMptVeNa29nOBNsIQ97.jpg',
    director: 'Denis Villeneuve',
    cast: ['Ryan Gosling', 'Harrison Ford', 'Ana de Armas', 'Sylvia Hoeks'],
    genres: ['Science Fiction', 'Drama', 'Mystery'],
    watched_date: '2023-11-15',
    personal_rating: 9.7,
    gut_reaction: 'The ultimate 3 AM rainy-night reverie on what it means to crave a soul you were never engineered to have.',
    full_review: 'Roger Deakins shoots neon mist and dust-choked Las Vegas orange ruins with the sacred reverence of Renaissance frescoes. Gosling delivers career-best understated melancholy as K, a man discovering he is not the chosen one—and choosing grace anyway. The film improves with every single rewatch.',
    mood_coordinates: { x: -80, y: -45 },
    custom_tags: ['Neon Noir', '3 AM Melancholy', 'Existential Dread', 'Atmospheric Peak'],
    dominant_color: '#e67329',
    rewatch_count: 6,
    created_at: '2023-11-16T04:15:00Z'
  },
  {
    id: 'bc7610fa-2384-4821-bcde-5109b8219404',
    tmdb_id: 965150,
    title: 'Aftersun',
    media_type: 'movie',
    release_year: 2022,
    runtime_minutes: 102,
    poster_url: 'https://image.tmdb.org/t/p/w780/6E3WzM92dYp2KkPZ3BcfG2VbE9G.jpg',
    backdrop_url: 'https://image.tmdb.org/t/p/original/b9h88rQ0fU0lQ28mC9g2ZlC2r7D.jpg',
    director: 'Charlotte Wells',
    cast: ['Paul Mescal', 'Frankie Corio', 'Celia Rowlson-Hall'],
    genres: ['Drama'],
    watched_date: '2023-01-20',
    personal_rating: 9.5,
    gut_reaction: 'The ghost of a holiday vacation reconstructed through camcorder fuzz and devastating unspoken grief.',
    full_review: 'Charlotte Wells captures the elusive texture of memory better than almost any debut filmmaker in history. The strobe-lit rave sequence set to Queen & Bowie’s "Under Pressure" captures the heartbreaking realization of seeing a parent as a vulnerable, drowning human being for the first time.',
    mood_coordinates: { x: -65, y: -92 },
    custom_tags: ['Emotional Devastation', 'Nostalgia Ache', 'Poetic Cinema', 'Mescal Peak'],
    dominant_color: '#3b82f6',
    rewatch_count: 2,
    created_at: '2023-01-21T09:00:00Z'
  },
  {
    id: '5d891b92-74c1-4fe1-bb23-99881122a505',
    tmdb_id: 95396,
    title: 'Severance',
    media_type: 'tv',
    release_year: 2022,
    runtime_minutes: 55,
    poster_url: 'https://image.tmdb.org/t/p/w780/p4p9pZqPcrkY7wV2jI3F5qO3bYw.jpg',
    backdrop_url: 'https://image.tmdb.org/t/p/original/9faGSFi5jam6pDhAzFb6SlBkrA7.jpg',
    director: 'Ben Stiller, Aoife McArdle',
    cast: ['Adam Scott', 'Patricia Arquette', 'John Turturro', 'Christopher Walken', 'Britt Lower'],
    genres: ['Drama', 'Mystery', 'Sci-Fi & Fantasy'],
    watched_date: '2024-02-18',
    personal_rating: 9.7,
    gut_reaction: 'The sharpest, most claustrophobic corporate nightmare ever televised, calibrated with millimeter perfection.',
    full_review: 'The sterile green carpets of Lumon Industries conceal the greatest psychological puzzle box since early Lost. Theodore Shapiro’s four-note piano motif haunts every hallway transition. The Season 1 finale is a 40-minute masterclass in unbearable, edge-of-the-seat tension.',
    mood_coordinates: { x: -85, y: -30 },
    custom_tags: ['Corporate Dystopia', 'Mind-Bender', 'Obsessive Television', 'Must Watch'],
    dominant_color: '#10b981',
    rewatch_count: 2,
    created_at: '2024-02-19T14:20:00Z'
  },
  {
    id: '67a80b33-912c-4933-a8fe-30018872c606',
    tmdb_id: 129,
    title: 'Spirited Away',
    media_type: 'anime',
    release_year: 2001,
    runtime_minutes: 125,
    poster_url: 'https://image.tmdb.org/t/p/w780/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
    backdrop_url: 'https://image.tmdb.org/t/p/original/Ab8mkHmkYADjU7wQiOkia9BzGvS.jpg',
    director: 'Hayao Miyazaki',
    cast: ['Rumi Hiiragi', 'Miyu Irino', 'Mari Natsuki', 'Takashi Naito'],
    genres: ['Animation', 'Family', 'Fantasy'],
    watched_date: '2023-12-25',
    personal_rating: 10.0,
    gut_reaction: 'Pure bathhouse sorcery and boundless childhood courage—the train ride on flooded tracks remains sacred cinema.',
    full_review: 'Miyazaki’s magnum opus operates with dream logic so flawless that every spirit, radish monster, and soot sprite feels grounded in ancient truth. Joe Hisaishi’s "One Summer’s Day" melody unlocks immediate tears. A film that cleanses the spirit every time you watch it.',
    mood_coordinates: { x: 35, y: 95 },
    custom_tags: ['Comfort Rewatch', 'Mythic Wonder', 'Studio Ghibli', 'Masterpiece'],
    dominant_color: '#ec4899',
    rewatch_count: 8,
    created_at: '2023-12-26T18:00:00Z'
  },
  {
    id: '71c89012-6632-47ef-a01b-99003311f707',
    tmdb_id: 76338,
    title: 'Succession',
    media_type: 'tv',
    release_year: 2018,
    runtime_minutes: 60,
    poster_url: 'https://image.tmdb.org/t/p/w780/7kig2iR51VlI3qM8x9GgK1pG9Xv.jpg',
    backdrop_url: 'https://image.tmdb.org/t/p/original/eU10YtYv65Xn29Z6EsmD6qF3Z2w.jpg',
    director: 'Jesse Armstrong, Mark Mylod',
    cast: ['Brian Cox', 'Jeremy Strong', 'Sarah Snook', 'Kieran Culkin', 'Matthew Macfadyen'],
    genres: ['Drama'],
    watched_date: '2023-05-30',
    personal_rating: 9.9,
    gut_reaction: 'King Lear in bespoke Italian suits, weaponizing vulgarity and trauma into television history.',
    full_review: 'Armstrong’s writing team produced the sharpest dialogue since David Mamet, laced with the tragic certainty that none of these poisoned billionaires can ever escape the orbit of their father’s cruel gravitational pull. Episode 3 of Season 4 ("Connor’s Wedding") redefined television realism in a single unbroken take.',
    mood_coordinates: { x: -45, y: -70 },
    custom_tags: ['Shakespearean Tragedy', 'Biting Dialogue', 'Peak TV', 'Masterclass'],
    dominant_color: '#d97706',
    rewatch_count: 3,
    created_at: '2023-05-31T08:00:00Z'
  },
  {
    id: '882f091c-1122-4988-bb33-77441199a808',
    tmdb_id: 666277,
    title: 'Past Lives',
    media_type: 'movie',
    release_year: 2023,
    runtime_minutes: 106,
    poster_url: 'https://image.tmdb.org/t/p/w780/k3waqVXSnvCZWfJYNtdamTgTtTA.jpg',
    backdrop_url: 'https://image.tmdb.org/t/p/original/2vFuG6bWGyQUzYS9d69UpNx57ao.jpg',
    director: 'Celine Song',
    cast: ['Greta Lee', 'Teo Yoo', 'John Magaro'],
    genres: ['Drama', 'Romance'],
    watched_date: '2023-08-14',
    personal_rating: 9.4,
    gut_reaction: 'An aching tribute to the parallel lives we leave behind at every crossroad of immigration and destiny.',
    full_review: 'Celine Song avoids all soap opera melodrama to present something infinitely more mature: three decent human beings speaking with radical honesty at a bar in New York City. The final walk to the Uber cab is one of the most agonizing, beautiful silences in contemporary film.',
    mood_coordinates: { x: -50, y: -20 },
    custom_tags: ['Quiet Heartbreak', 'In-Yun', 'Poetic Yearning', 'A24 Gold'],
    dominant_color: '#0284c7',
    rewatch_count: 2,
    created_at: '2023-08-15T11:45:00Z'
  },
  {
    id: '99120033-55aa-498b-9022-334455667788',
    tmdb_id: 76341,
    title: 'Mad Max: Fury Road',
    media_type: 'movie',
    release_year: 2015,
    runtime_minutes: 120,
    poster_url: 'https://image.tmdb.org/t/p/w780/8tZYtuWezp8JbcsvHYO0O46tFbo.jpg',
    backdrop_url: 'https://image.tmdb.org/t/p/original/nlCHUW2Y9XWbuR19NNipUQZik1F.jpg',
    director: 'George Miller',
    cast: ['Tom Hardy', 'Charlize Theron', 'Nicholas Hoult', 'Hugh Keays-Byrne'],
    genres: ['Action', 'Adventure', 'Science Fiction'],
    watched_date: '2024-01-10',
    personal_rating: 9.8,
    gut_reaction: 'A two-hour flame-throwing symphony of pure kinetic fury that makes all other action movies feel asleep.',
    full_review: 'George Miller turned a desert chase into visual poetry with practical stuntwork that feels miraculous in an era of weightless CGI. Charlize Theron’s Imperator Furiosa instantly carved her name alongside Ellen Ripley in the pantheon of action cinema heroes.',
    mood_coordinates: { x: 92, y: 55 },
    custom_tags: ['Adrenaline Injected', 'Kinetic Masterclass', 'Pure Action', 'Holy Stunts'],
    dominant_color: '#f59e0b',
    rewatch_count: 7,
    created_at: '2024-01-11T20:10:00Z'
  },
  {
    id: 'ab334455-7788-4999-1122-aabbccddeeff',
    tmdb_id: 569094,
    title: 'Spider-Man: Across the Spider-Verse',
    media_type: 'movie',
    release_year: 2023,
    runtime_minutes: 140,
    poster_url: 'https://image.tmdb.org/t/p/w780/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg',
    backdrop_url: 'https://image.tmdb.org/t/p/original/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg',
    director: 'Joaquim Dos Santos, Kemp Powers, Justin K. Thompson',
    cast: ['Shameik Moore', 'Hailee Steinfeld', 'Oscar Isaac', 'Daniel Kaluuya'],
    genres: ['Animation', 'Action', 'Adventure', 'Sci-Fi'],
    watched_date: '2023-06-03',
    personal_rating: 9.5,
    gut_reaction: 'Every individual frame is a high-octane graphic design manifesto painted in emotional watercolors.',
    full_review: 'The Gwen Stacy watercolor mood-shifting world in the opening 20 minutes alone is more artistically daring than the last decade of studio animation. Daniel Kaluuya’s Hobie Brown (Spider-Punk) stealing every scene with torn-paper punk aesthetics is cinema at its most joyful.',
    mood_coordinates: { x: 80, y: 72 },
    custom_tags: ['Visual Overload', 'Animation Revolution', 'Kinetic Art', 'Must Experience'],
    dominant_color: '#8b5cf6',
    rewatch_count: 3,
    created_at: '2023-06-04T16:00:00Z'
  },
  {
    id: 'cc221100-3344-4888-9900-112233445566',
    tmdb_id: 467244,
    title: 'The Zone of Interest',
    media_type: 'movie',
    release_year: 2023,
    runtime_minutes: 105,
    poster_url: 'https://image.tmdb.org/t/p/w780/hUu9zyZmDD8VZegKi1iK1Vk0RYS.jpg',
    backdrop_url: 'https://image.tmdb.org/t/p/original/8u1bXjYp2K8fXjEw8b3t3q3N8Z.jpg',
    director: 'Jonathan Glazer',
    cast: ['Christian Friedel', 'Sandra Hüller', 'Johann Karthaus'],
    genres: ['Drama', 'History', 'War'],
    watched_date: '2024-02-05',
    personal_rating: 9.6,
    gut_reaction: 'The most chilling and necessary examination of human complicity ever conceived, told entirely through off-camera sound.',
    full_review: 'Glazer avoids all Hollywood dramatization to show the mundane garden parties and flower beds directly against the Auschwitz wall. Johnnie Burn’s sound design is an overwhelming, horrifying monument of human evil that refuses to let the viewer look away from their own moral inertia.',
    mood_coordinates: { x: -95, y: -98 },
    custom_tags: ['Haunting Sound Design', 'Banality of Evil', 'Unsettling', 'Chilling Masterpiece'],
    dominant_color: '#64748b',
    rewatch_count: 1,
    created_at: '2024-02-06T13:00:00Z'
  },
  {
    id: 'dd445566-7788-4111-2233-445566778899',
    tmdb_id: 915935,
    title: 'Anatomy of a Fall',
    media_type: 'movie',
    release_year: 2023,
    runtime_minutes: 151,
    poster_url: 'https://image.tmdb.org/t/p/w780/kQs6keheMwCxJxrzV03VUOOqaXx.jpg',
    backdrop_url: 'https://image.tmdb.org/t/p/original/9n2tJBplPbg9v059RtU3aV0nCgV.jpg',
    director: 'Justine Triet',
    cast: ['Sandra Hüller', 'Swann Arlaud', 'Milo Machado Graner', 'Antoine Reinartz'],
    genres: ['Drama', 'Crime', 'Mystery'],
    watched_date: '2023-10-12',
    personal_rating: 9.3,
    gut_reaction: 'A dissecting scalpel turned on the invisible fictions and compromises that hold marriage together.',
    full_review: 'Sandra Hüller delivers a towering performance full of ambiguity and prickly intellect. The courtroom scenes deconstruct how language and translation can weaponize human memory, while 50 Cent’s "P.I.M.P." steel-drum instrumental becomes an unforgettable plot device.',
    mood_coordinates: { x: -82, y: -38 },
    custom_tags: ['Courtroom Dissection', 'Ambiguity Masterclass', 'Chilling', 'Palme dOr'],
    dominant_color: '#0f766e',
    rewatch_count: 2,
    created_at: '2023-10-13T19:25:00Z'
  },
  {
    id: 'ee112233-4455-6677-8899-aabbccddeeff',
    tmdb_id: 1429,
    title: 'Attack on Titan',
    media_type: 'anime',
    release_year: 2013,
    runtime_minutes: 24,
    poster_url: 'https://image.tmdb.org/t/p/w780/hTP1DtLGFamjfu8WqjnuQdP1n4i.jpg',
    backdrop_url: 'https://image.tmdb.org/t/p/original/b9h88rQ0fU0lQ28mC9g2ZlC2r7D.jpg',
    director: 'Tetsurō Araki',
    cast: ['Yuki Kaji', 'Yui Ishikawa', 'Marina Inoue', 'Hiroshi Kamiya'],
    genres: ['Animation', 'Action', 'Sci-Fi & Fantasy'],
    watched_date: '2023-11-20',
    personal_rating: 9.9,
    gut_reaction: 'A monumental, generational mythos that turns apocalyptic warfare into a devastating essay on cycle of violence.',
    full_review: 'Hajime Isayama and Wit Studio/MAPPA constructed television’s greatest structural mystery. Hiroyuki Sawano’s roaring orchestral choral score elevates every odm gear flight into sublime terror. The basement reveal remains one of modern fiction’s greatest paradigm shifts.',
    mood_coordinates: { x: -30, y: -80 },
    custom_tags: ['Existential Dread', 'Epic Odyssey', 'Anime Masterpiece', 'Must Watch'],
    dominant_color: '#854d0e',
    rewatch_count: 4,
    created_at: '2023-11-21T15:00:00Z'
  },
  {
    id: 'ff223344-5566-7788-9900-aabbccddeeff',
    tmdb_id: 105248,
    title: 'Cyberpunk: Edgerunners',
    media_type: 'anime',
    release_year: 2022,
    runtime_minutes: 24,
    poster_url: 'https://image.tmdb.org/t/p/w780/7jswOcU8y60zL15jL45KgnqH4yB.jpg',
    backdrop_url: 'https://image.tmdb.org/t/p/original/70Rm9m1mb9T05115d7v71NDNswE.jpg',
    director: 'Hiroyuki Imaishi',
    cast: ['KENN', 'Aoi Yuki', 'Hiroki Touchi', 'Michiko Kaiden'],
    genres: ['Animation', 'Sci-Fi & Fantasy', 'Action'],
    watched_date: '2022-09-25',
    personal_rating: 9.7,
    gut_reaction: 'Studio Trigger weaponizing hyper-stylized neon hyperviolence into a heartbreaking moonshot romance.',
    full_review: 'In only 10 episodes, Trigger crafts Night City with more emotional resonance than a 100-hour RPG. "I Really Want to Stay at Your House" will forever trigger involuntary weeping. Lucy and David on the virtual moon surface is pure animated poetry.',
    mood_coordinates: { x: 75, y: -65 },
    custom_tags: ['Neon Noir', 'Emotional Devastation', 'Visual Overload', 'Sci-Fi Royalty'],
    dominant_color: '#facc15',
    rewatch_count: 3,
    created_at: '2022-09-26T21:00:00Z'
  },
  {
    id: 'aa998877-6655-4433-2211-001122334455',
    tmdb_id: 93405,
    title: 'Squid Game',
    media_type: 'kdrama',
    release_year: 2021,
    runtime_minutes: 55,
    poster_url: 'https://image.tmdb.org/t/p/w780/dDlGgwXb6823L5nQ6lF3x7k727Y.jpg',
    backdrop_url: 'https://image.tmdb.org/t/p/original/xJHokMbljvjADYdit5fK5VQsXEG.jpg',
    director: 'Hwang Dong-hyuk',
    cast: ['Lee Jung-jae', 'Park Hae-soo', 'Wi Ha-joon', 'Jung Ho-yeon'],
    genres: ['Drama', 'Mystery', 'Action & Adventure'],
    watched_date: '2021-10-02',
    personal_rating: 9.5,
    gut_reaction: 'The most electrifying, razor-sharp critique of late-stage capitalist debt traps disguised as candy-colored children’s games.',
    full_review: 'Episode 6 ("Gganbu") is a masterwork of television acting—an unsparing exploration of human loyalty under absolute existential desperation. Lee Jung-jae is magnetic as Seong Gi-hun, finding humanity in the grimmest arena imaginable.',
    mood_coordinates: { x: -60, y: -75 },
    custom_tags: ['Capitalist Dystopia', 'Mind-Bender', 'Edge of Seat', 'Phenomenon'],
    dominant_color: '#ec4899',
    rewatch_count: 2,
    created_at: '2021-10-03T18:30:00Z'
  },
  {
    id: 'bb887766-5544-3322-1100-ffeeddccbbaa',
    tmdb_id: 94796,
    title: 'Crash Landing on You',
    media_type: 'kdrama',
    release_year: 2019,
    runtime_minutes: 80,
    poster_url: 'https://image.tmdb.org/t/p/w780/k7NlK6lX9cT0iA2P3N3WvE4F6uG.jpg',
    backdrop_url: 'https://image.tmdb.org/t/p/original/ilRyAZstrMptVeNa29nOBNsIQ97.jpg',
    director: 'Lee Jeong-hyo',
    cast: ['Hyun Bin', 'Son Ye-jin', 'Seo Ji-hye', 'Kim Jung-hyun'],
    genres: ['Drama', 'Romance', 'Comedy'],
    watched_date: '2020-03-15',
    personal_rating: 9.6,
    gut_reaction: 'The gold standard of sweeping television romance across the DMZ that ruins all other romance dramas forever.',
    full_review: 'Hyun Bin and Son Ye-jin have incandescent, real-life chemistry that radiates through every single scene. The ensemble cast of North Korean village ahjummas and Captain Ri’s ducklings soldiers provide unmatched comedic warmth and genuine emotional weight.',
    mood_coordinates: { x: 45, y: 88 },
    custom_tags: ['Romantic Peak', 'Comfort Rewatch', 'Tearjerker', 'K-Drama Masterpiece'],
    dominant_color: '#f43f5e',
    rewatch_count: 4,
    created_at: '2020-03-16T12:00:00Z'
  }
];

export const GENRE_LIST = [
  'All',
  'Science Fiction',
  'Drama',
  'Action',
  'Adventure',
  'Animation',
  'Mystery',
  'Romance',
  'Comedy',
  'History',
  'Crime'
];

export const TAG_LIST = [
  'All',
  'Mind-Melting',
  'Audio Masterpiece',
  'Neon Noir',
  '3 AM Melancholy',
  'Existential Catharsis',
  'Comfort Rewatch',
  'Corporate Dystopia',
  'Visual Overload',
  'Shakespearean Tragedy',
  'Quiet Heartbreak',
  'Adrenaline Injected'
];
